api_message_list:
  path:     /messages
  defaults: { _controller: MessageBundle:Default:index }
  methods:  [GET, HEAD]

api_message_create:
  path:     /messages
  defaults: { _controller: MessageBundle:Default:create }
  methods:  [POST]